#jamell
#4/22/2024/


name1 = input("Please enter a name: ")
name2 = input("Please enter a name: ")
name3 = input("Please enter a name: ")
name4 = input("Please enter a name: ")
name5 = input("Please enter a name: ")
name6 = input("Please enter a name: ")
name7 = input("Please enter a name: ")
name8 = input("Please enter a name: ")
name9 = input("Please enter a name: ")
name10 = input("Please enter a name: ")
name11 = input("Please enter a name: ")
name12 = input("Please enter a name: ")
name13 = input("Please enter a name: ")
name14 = input("Please enter a name: ")
name15 = input("Please enter a name: ")
name16 = input("Please enter a name: ")
name17 = input("Please enter a name: ")
name18 = input("Please enter a name: ")
name19 = input("Please enter a name: ")
name20 = input("Please enter a name: ")
print("here are the names that you listed: osa")
print(name1)
print(name2)
print(name3)
print(name4)
print(name5)
print(name6)
print(name7)
print(name8)
print(name9)
print(name10)
print(name11)
print(name12)
print(name13)
print(name14)
print(name15)
print(name16)
print(name17)
print(name18)
print(name19)
print(name20)